### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by simonschwitzky** [willnationsdev/godot-skills#1]
Wondering if there ever was a stable release of the skill system or if it's still maintained somewhere? Cheers

**Comment by willnationsdev** [comment]
The short answer is "no". The long answer is "maybe eventually".

I have a game that I would like to make that is highly systemic and that therefore could benefit a lot from using an API such as the one proposed here (though, likely implemented in a very different way). This project was meant to act as a way of open-sourcing my development of such a skill framework separately from its use in an actual game project of my own.

However, before I fully engaged in developing that project, I got waylaid by my misgivings of Godot's architecture and how it restricted my ability to program this stuff the way I would have liked to. From there, I transitioned into focusing on engine development and making the low-level structural changes I required to actually build the Godot tooling & framework I desired for my game (including this project).

Godot 4.0 is looking thus far like it'll be able to accommodate most of my needs, so I may begin resuming work on that game soon after it is launched, in which case, we may see this project resume activity (though, now that Godex is out, I'm wondering to what extent I could/should leverage a GDExtension port of that to use as a dependency of this project).

The [willnationsdev/godot-resqdb](https://github.com/willnationsdev/godot-resqdb), [willnationsdev/godot-spreadsheet](https://github.com/willnationsdev/godot-spreadsheet), and [willnationsdev/godot-journey](https://github.com/willnationsdev/godot-journey) projects are all in a similar hiatus position since they are all ultimately related to the same game project concept: data warehousing/querying, spreadsheet for displaying queries, pluggable quest/dialogue system w/ editor(s), and flexible/easy-to-use skill system, each of which contribute to the systemic RPG simulation game I plan on making.

Truth be told, I just started on a 2-week vacation today, and I *would* have started work on the aforementioned projects (likely in order of spreadsheet -> resqdb -> journey -> skills), but had another side-project that's actually for a more imminently needed business opportunity, so I kinda had to prioritize that. So while "yes", this repository and the others are certainly still on my mind, "no" they don't have any active development at this time (hopefully soon though).

Thank you for your interest though!
